version: "3"
services:
    webapp:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Titouan20"
            ACCEPT_EULA: "Y"