version: "3"
services:
    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - "8080:80"
    mysql-development:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: helloworld
            MYSQL_DATABASE: dev_dashboard
        ports:
        - "3308:3306"
        expose:
            - '3306'